config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do
	    resources :todo_items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "todo_lists#index"
  
  #map.log_out 'logout', :controller => 'sessions', :action => 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  scope :completed, -> do
    where(completed: true)
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_items

  def percent_complete
    return 0 if total_items == 0
    (100 * completed_items.to_f / total_items).round(1)
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end

  def total_items
    @total_items ||= todo_items.count
  end

  def status
    case percent_complete.to_i
    when 0
      'Not started'
    when 100
      'Complete'
    else
      'In progress'
    end
  end

  def badge_color
    case percent_complete.to_i
    when 0
      'dark'
    when 100
      'info'
    else
      'primary'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :todo_lists

  def balance
    user = current_user.id
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
end

app/controllers/country_controller.rb
class CountryController < ApplicationController
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET todo_lists/1/todo_items
  def index
    @todo_items = @todo_list.todo_items
  end

  # GET todo_lists/1/todo_items/1
  def show
  end

  # GET todo_lists/1/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.build
  end

  # GET todo_lists/1/todo_items/1/edit
  def edit
  end

  # POST todo_lists/1/todo_items
  def create
    @todo_item = @todo_list.todo_items.build(todo_item_params)

    if @todo_item.save
      redirect_to([@todo_item.todo_list, @todo_item], notice: 'Todo item was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT todo_lists/1/todo_items/1
  def update
    if @todo_item.update_attributes(todo_item_params)
      redirect_to([@todo_item.todo_list, @todo_item], notice: 'Todo item was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE todo_lists/1/todo_items/1
  def destroy
    @todo_item.destroy

    redirect_to todo_list_todo_items_url(@todo_list)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.where(user_id: current_user.id).find(params[:todo_list_id])


    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
      
    end

    # Only allow a trusted parameter "white list" through.
    def todo_item_params
      params.require(:todo_item).permit(:description, :completed, :complited_at, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 
  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.where(user_id: current_user.id)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_item = TodoItem.new
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
    
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.user_id = current_user.id
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to root_url, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params).where(user_id: current_user.id)
        format.html { redirect_to root_url, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
     @todo_list = TodoList.where(user_id: current_user.id).find(params[:id]) 
     
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/_menu.html.erb
<div id="right_menu" class="container">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Task Manager <%= current_user.email %> </a>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


      <li class="nav-item dropdown">
          <%= link_to 'Новый проект', new_todo_list_path, class: 'nav-link dropdown-toggle' %>

      </li>
      <li class="nav-item">
        <%= link_to ' Выход', destroy_user_session_path, method: :delete,  class: 'nav-link'%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

</div>

app/views/layouts/_notice.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_scripts.html.erb
 <!-- jQuery  -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/tether.min.js"></script><!-- Tether for Bootstrap -->
        <script src="assets/js/popper.min.js"></script>
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/modernizr.min.js"></script>
        <script src="assets/js/detect.js"></script>
        <script src="assets/js/fastclick.js"></script>
        <script src="assets/js/jquery.slimscroll.js"></script>
        <script src="assets/js/jquery.blockUI.js"></script>
        <script src="assets/js/waves.js"></script>
        <script src="assets/js/jquery.nicescroll.js"></script>
        <script src="assets/js/jquery.scrollTo.min.js"></script>

        <!-- App js -->
        <script src="assets/js/app.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><!-- End Required meta tags -->
    <!-- Begin SEO tag -->
    <title> менеджер проектов V.1.0 </title>

    <!-- FAVICONS -->
    <link rel="apple-touch-icon" sizes="144x144" href="assets/apple-touch-icon.png">
    <link rel="shortcut icon" href="assets/favicon.ico">
    <meta name="theme-color" content="#3063A0"><!-- End FAVICONS -->
    <!-- GOOGLE FONT -->
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,500,600" rel="stylesheet"><!-- End GOOGLE FONT -->
    <!-- BEGIN PLUGINS STYLES -->

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

 <style><%= yield :stylesheets %></style>

    <script>
      var skin = localStorage.getItem('skin') || 'default';
      var disabledSkinStylesheet = document.querySelector('link[data-skin]:not([data-skin="' + skin + '"])');
      // Disable unused skin immediately
      disabledSkinStylesheet.setAttribute('rel', '');
      disabledSkinStylesheet.setAttribute('disabled', true);
      // add loading class to html immediately
      document.querySelector('html').classList.add('loading');
    </script><!-- END THEME STYLES -->
  </head>
  <!-- Favicons -->


  <body>


    <!-- .app -->
    <div class="app has-fullwidth">
      <!--[if lt IE 10]>
      <div class="page-message" role="alert">You are using an <strong>outdated</strong> browser. Please <a class="alert-link" href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</div>
      <![endif]-->
     <!-- .app-header -->
      <!-- .app-header -->

      <% if user_signed_in? %>
        <%= render :partial => "layouts/menu"  %>
      <% end %>

    
      <!-- /.app-header -->
      <!-- .app-main -->
      <main class="app-main">
        <!-- .wrapper -->
        <div class="wrapper">

          <div class="container">
           <%= render :partial => "layouts/notice"  %>
               <div id="content"><%= content_for?(:content) ? yield(:content) : yield %></div>
          </div>

          <!-- .page -->

        </div><!-- /.wrapper -->
        <!-- .app-footer -->

      </main><!-- /.app-main -->
    </div><!-- /.app -->
    <!-- BEGIN BASE JS -->


  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_item.todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-fild">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :complited_at %><br />
    <%= f.datetime_select :complited_at %>
  </div>
  <div class="field">
    <%= f.label :todo_list %><br />
    <%= f.text_field :todo_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<div class="jumbotron">
  <%= link_to 'Показать', [@todo_item.todo_list, @todo_item] %> |
  <%= link_to 'Весь список', todo_list_todo_items_path(@todo_item.todo_list) %>
  
  <h1>Редактировать задачу</h1>

  <%= render 'form' %>




</div>

app/views/todo_items/index.html.erb
 <%= render :partial => "layouts/notice"  %>
<div class="jumbotron">
  <h1>Список задач по проекту</h1>

  <table class = "table ">
    <tr>
      <th>Description</th>
      <th>Completed</th>
      <th>Complited at</th>
      <th>Todo list</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @todo_items.each do |todo_item| %>
    <tr>
      <td><%= todo_item.description %></td>
      <td><%= todo_item.completed %></td>
      <td><%= todo_item.complited_at %></td>
      <td><%= todo_item.todo_list %></td>
      <td><%= link_to 'Просмотр', [todo_item.todo_list, todo_item] , class: 'btn btn-primary' %></td>
      <td><%= link_to 'Редактировать', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item) %></td>
      <td><%= link_to 'Удалить', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'Новая задача', new_todo_list_todo_item_path(params[:todo_list_id]), class: 'btn btn-success' %>


  <%= link_to 'назад', todo_lists_path, class: 'btn btn-secondary'  %>
</div>

app/views/todo_items/new.html.erb
<div class="jumbotron">
  <%= link_to 'Список задач', todo_list_todo_items_path(@todo_item.todo_list) , class: 'btn btn-primary'%>
  <h3>Создать новую задачу</h3>

  <%= render 'form' %>




</div>

app/views/todo_items/show.html.erb
<div class="jumbotron">
  <%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_item.todo_list, @todo_item, class: 'btn btn-success')%> |
  <%= link_to 'Список задач', todo_list_todo_items_path(@todo_item.todo_list), class: 'btn btn-primary' %>
  <p id="notice"><%= notice %></p>

  <p>
    <b>Description:</b>
    <%= @todo_item.description %>
  </p>

  <p>
    <b>Completed:</b>
    <%= @todo_item.completed %>
  </p>

  <p>
    <b>Complited at:</b>
    <%= @todo_item.complited_at %>
  </p>

</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.text_field :user_id  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<div class="jumbotron">
  <h1>Редактирование названия проекта</h1>

  <%= render 'form', todo_list: @todo_list %>

  <%= link_to 'Просмотр', @todo_list, class: 'btn btn-primary' %> |
  <%= link_to 'Вернуться к проектам', todo_lists_path, class: 'btn btn-primary' %>


</div>

app/views/todo_lists/index.html.erb
<% if user_signed_in? %>

<div class="jumbotron">
  <div class="card-body">
        <ul class= 'list-group'>
          <%  @todo_lists.each do |todo_list| %>
             
              <%= link_to todo_list, class: 'text-decoration-none'  do %>
                  <li class="list-group-item d-flex justify-content-between">
                    <div>
                      <h6 class='m-0 text-dark'>
                        <b><%= todo_list.title  %></b>
                        <span class="badge badge-<%= todo_list.badge_color %>"><%= todo_list.status %></span>
                      </h6>

                      <p class='text-secondary m-0 text-dark'><small> <%= todo_list.percent_complete %> % Complete (<%=
                        todo_list.completed_items %> / <%= todo_list.total_items %> Todo Items) </small></p>
                    </div>

                  </li>
              <% end %>
              
          <% end %>
        </ul>
   </div>

</div>

<% end %>

app/views/todo_lists/new.html.erb
<div class="jumbotron">

  <%= link_to 'Список проектов', todo_lists_path , class: 'btn btn-primary'%>
  <h1>Создать новый проект</h1>

  <%= render 'form', todo_list: @todo_list %>




</div>

app/views/todo_lists/show.html.erb
 

<div class="card-header ">
  <div class="row">
    <div class="col-1">
      <%= link_to todo_lists_path, class: 'btn btn-dark' do %>
        <i class='fa fa-angle-left'></i>
      <% end %>
    </div>
    <div class="col-11 ">
      <div class="d-flex justify-content-between">
        <div>
          <h5 class='m-0'>
            <b><%= @todo_list.title %></b>
            <span class="badge badge-<%= @todo_list.badge_color %>"><%= @todo_list.status %> </span>
          </h5>
          <p class='text-secondary m-0'> <small> <%= @todo_list.percent_complete %> % Complete (<%= @todo_list.completed_items %>/<%= @todo_list.total_items %> Todo Items) </small></p>
        </div>
        <div>
          <%= link_to 'Edit', edit_todo_list_path(@todo_list), class: 'btn btn-secondary'%>
        </div>
      </div>
    </div>
  </div>


</div>
<div class="card-body">
  <div class="progress mb-4">
    <div class="progress-bar bg-info" role="progressbar" style="width:<%= @todo_list.percent_complete %>%" aria-valuenow="<%= @todo_list.percent_complete %>" aria-valuemin="0" aria-valuemax="100">
    </div>
  </div>
  <%= form_for([@todo_list, @todo_item]) do |f| %>
    <div class="input-group mb-4">
          <%= f.text_field :description, class: 'form-control', placeholder: 'Add a todo item' %>
          <div class="input-group-append">
          <%= f.submit "Add", class: "btn btn-primary input-group-btn" %>
      </div>
    </div>
  <% end %>


  <ul class= 'list-group'>
     <% @todo_list.todo_items.each do |todo_item| %>
        <% if todo_item.completed? %>
           <li class='list-group-item bg-dark'>
            <div class="d-flex justify-content-between">
              <%= link_to '#', class: 'btn btn-dark', data: { reflex: 'click->TodoItem#mark_incomplete', id: todo_item.id}  do %>
              <i class='fa fa-check'></i>
              <span>
              <% end %>
                <em><%= todo_item.description %></em>
              </span>
              <div class="">
              <%= link_to '', [todo_item.todo_list, todo_item], class: 'fa fa-edit' %>
              <%= link_to '', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item), class: 'fa fa-eye'  %>
              <%= link_to '', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-eraser' %>



              </div>
            </div>
          </li>
        <% else%>
          <li class='list-group-item '>
           <div class="d-flex justify-content-between">
             <%= link_to '#', class: 'btn btn-darklight', data: { reflex: 'click->TodoItem#mark_complete', id: todo_item.id}  do %>
               <i class='fa fa-undo'></i>
             <% end %>
             <span>
               <em><%= todo_item.description %></em>
             </span>
              <div class="">
                <%= link_to '', [todo_item.todo_list, todo_item], class: 'fa fa-edit' %>
                <%= link_to '', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item), class: 'fa fa-eye'  %>
                <%= link_to '', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-eraser' %>


              </div>


           </div>
         </li>
        <% end %>
     <% end %>
  </ul>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
  <h1>Список пользователей </h1>

  <table class = "table table-bordered">
    <tr>
      <th>Description</th>
      <th>Completed</th>
      <th>Complited at</th>
      <th>Todo list</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= todo_item.description %></td>
      <td><%= todo_item.completed %></td>
      <td><%= todo_item.complited_at %></td>
      <td><%= todo_item.todo_list %></td>
      <td><%= link_to 'Просмотр', [todo_item.todo_list, todo_item] , class: 'btn btn-primary' %></td>
      <td><%= link_to 'Редактировать', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item) %></td>
      <td><%= link_to 'Удалить', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'Новая задача', new_todo_list_todo_item_path(params[:todo_list_id]), class: 'btn btn-success' %>


  <%= link_to 'назад', todo_lists_path, class: 'btn btn-secondary'  %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>